# Workspace
workspace 1 output DP-2

# Bar
set $barfontsize 11
set $barheight 27
set $labelmode ~/.config/sway/handlers/metrics-desktop.sh

# Set Theme
# include ~/.config/sway/themes/pinky.conf # pinky
include ~/.config/sway/themes/linux.conf # blacky

# Set stuff for my monitor
output DP-2 pos 0 0
output DP-2 mode 1920x1080@144.000Hz

output DP-3 pos 1920 0
output DP-3 mode 1920x1080@144.000Hz

# I use this agent, you can use anything you want
exec /usr/bin/lxqt-policykit-agent

# For Hubstaff (job stuff)
exec dbus-send --session \
  --print-reply=literal \
  --dest=org.freedesktop.impl.portal.PermissionStore \
  /org/freedesktop/impl/portal/PermissionStore \
  org.freedesktop.impl.portal.PermissionStore.SetPermission \
  string:'screenshot' \
  boolean:'true' \
  string:'screenshot' \
  string:'netsoft-com.netsoft.hubstaff' \
  array:string:'yes'
