# xgl off
xwayland disable

# bar configs
set $barfontsize 16
set $barheight 32
set $labelmode ~/.config/sway/handlers/metrics-battery.sh

# include ~/.config/sway/themes/pinky.conf # pinky
include ~/.config/sway/themes/linux.conf # blacky
