exec_always cp ~/.config/foot/themes/pinky.ini ~/.config/foot/foot.ini
exec_always echo '@theme "~/.config/rofi/themes/pinky"' >& ~/.config/rofi/config.rasi

output * bg ~/.config/sway/imgs/black-tesseract.png fill

bar {
  position top
  font pango:ComicMono $barfontsize
  height $barheight

  # Label metrics
  status_command $labelmode

  colors {
    statusline #ba8f9e
    background #edd9e0
    inactive_workspace #edd9e0 #edd9e0 #ba8f9e
    focused_workspace #ba8f9e #ba8f9e #edd9e0
  }
}
